# Generated by Django 6.0.7 on 2026-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='horoscope',
            constraint=models.UniqueConstraint(fields=('zodiac', 'date'), name='unique_daily_horoscope'),
        ),
    ]
