# Generated by Django 6.0.7 on 2026-08-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_premiumsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
