# Generated by Django 6.0.7 on 2026-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0006_janamkundli'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDarshan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('mahakaleshwar', 'Mahakaleshwar'), ('balaji', 'Balaji'), ('khatu_shyam', 'Khatu Shyam Ji'), ('vaishno_devi', 'Vaishno Devi')], max_length=30)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='darshan/')),
                ('youtube_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
