# Generated by Django 6.0.7 on 2026-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0007_dailydarshan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydarshan',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='darshan/videos/'),
        ),
    ]
